check_task:
  container:
    image: fnichol/check-shell:latest
  setup_script: apk add curl jq py3-jsonschema
  check_script: make check

ci_finished_task:
  name: ci-finished
  depends_on:
    - check
  container:
    image: alpine:3
  clone_script: mkdir -p "$CIRRUS_WORKING_DIR"
  success_script: /bin/true
